### ISSUE TITLE
CSV string returned prepends numbering to headers

### ISSUE THREAD

**Issue by iman-nebulr** [mrodrig/json-2-csv#202] opened 2021-07-28 10:52 UTC
## Background Information
- Module Version: `3.11.1`
- Node/Browser Version: `12.19.0 `

The issue I'm reporting is with:
- [X] json2csv
- [ ] csv2json

I have...
- [X] searched to see if an issue has already been reported.
- [X] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [X] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
Headers do not have prepended numbering

## Actual Behavior
json2csvAsync prepends numbering to headers

## Data Sample 
CSV:
```csv
0.First name;1.City
```

(or)

JSON:
```json

```

## Code Example
```javascript
// Please include a simple example to replicate the issue
let converter = require('json-2-csv');

I think this is just an undocumented usability issue
```

**Comment by mrodrig** [comment] 2021-07-29 04:39
Thanks for reporting this @iman-nebulr. Could you please provide a code example with test JSON data that reproduces this issue? I'm unable to reproduce this issue on version `3.14.1` (latest on NPM). 

Something like this would be great:

```javascript
import converter from 'json-2-csv';

const csv = await converter.json2csvAsync([
    {
        "First name": "Joe",
        "City": "Boston"
      }
]);

console.log(csv);
```

In this example, I'm seeing the following CSV output:

```
First name,City
Joe,Boston
```

**Comment by mrodrig** [comment] 2021-08-01 03:52
Closing this, but please feel free to re-open it with a code example if you're still running into this.

**Closed by mrodrig** 2021-08-01 03:52 UTC
Labels: waiting response

**Comment by iman-nebulr** [comment] 2021-08-02 09:10
Ok so I found what I was doing

My issue was that I had a structure that included a list of objects like the one below

let data = [
  [
    {
      Name: 'Joe'
    },
    {
      LastName: 'Johnson'
    }
  ],
  [
    {
      Name: 'Mary'
    },
    {
      LastName: 'Johnson'
    }
  ]
];

Here is a [code example](https://stackblitz.com/edit/typescript-bwis4f?file=index.ts)

I would not say it is an issue but if it needs documentation I can be of help
