### ISSUE TITLE
doesnt escape existing characters

### ISSUE THREAD

**Issue by ycheapopo** [mrodrig/json-2-csv#50] opened 2015-11-29 07:52 UTC
if input already has the delimeter character, input data is not escaped

**Comment by mrodrig** [comment] 2015-12-02 15:45
Thanks for reporting this @ycheapopo.  Are you referring to the json2csv or csv2json functionality?  Also, could you provide a quick example for me to look at so I can figure out exactly what the problem is?

Thanks!

**Comment by ycheapopo** [comment] 2015-12-02 16:10
I’m sorry, I should have asked it as a feature request:

I am using json2csv as transformation to csv, where later I can load these files as csv files to a SQL database.

Everything works fine, however if the input text has a value of the delimiter then the SQL database fails.


Suggestion: have an option to the serialiser that if it encounters the delimiter already input in text, it would escape it.

Workaround i have used: using a more elaborate delimiter with a few letters to minimise chance of this happening.

However, as I don’t control the input there is a rare chance it would occur.

tx for your time (I thought you might be interested in the exact use case).

**Comment by mrodrig** [comment] 2015-12-03 01:36
Thanks for the update and the detailed use case.  I'll definitely take a look at implementing this functionality.  Hopefully I will be able to get to this soon, but I might have to push it out for a week or two since final exams are coming up soon.  Thanks again!

**Comment by mrodrig** [comment] 2015-12-07 15:16
Quick question @ycheapopo: have you tried the wrap delimiter option?  I'm guessing SQL works fine if the CSV has the fields wrapped in quotes, but will fail if it encounters CSV such as this (specifically because of the last line having more values than fields):
```csv
test,test2,test3
v1,v2,v4
v5,z9,q17,a89
```

When using the wrap delimiter (example shown below), the CSV is output like this:
```csv
"test","test2","test3"
"v1","v2","v4"
"v5,z9","q17","a89"
```

Example:
```javascript
var converter = require('json-2-csv');

var json = [
    {
        test: 'v1',
        test2: 'v2',
        test3: 'v4'
    },
    {
        test: 'v5,z9',
        test2: 'q17',
        test3: 'a89'
    }
];

var json2csvCallback = function (err, csv) {
    if (err) throw err;
    console.log(csv);
};

converter.json2csv(json, json2csvCallback, {DELIMITER: { WRAP: '"'}});
```

Please let me know if this works.  In a future version, I think I will make the default wrap delimiter a double quote (") to avoid this and other related issues.

**Comment by mrodrig** [comment] 2015-12-18 14:38
I'm going to close this for now.  If setting the DELIMITER.WRAP value in options the provided options to `"` doesn't work for some reason (example in previous post), please let me know.  Thanks!

**Closed by mrodrig** 2015-12-18 14:38 UTC
Labels: enhancement, waiting response
